

# version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: weather_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d weather_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  weather_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_service
    restart: always
    secrets:
      - openweather_api_key
    environment:
      - DB_HOST=postgres
      - DB_NAME=weather_data
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./weather_service.py:/app/weather_service.py
      - ./schema.sql:/app/schema.sql

secrets:
  openweather_api_key:
    file: ./openweather_api_key.txt
    
volumes:
  postgres_data:
    driver: local
